### ISSUE TITLE
Publish v0.1

### ISSUE THREAD

**Issue by xuganyu96** [xuganyu96/untitled-badminton-app#28]
For v0.1 release, this app will be hosted on an AWS EC2 instance that runs a few containers:

* `bad-scheduler` for the scheduler node
* `bad-webserver` for the webserver node
* `postgres` for the database
* possibly an NginX container

- [x] Adapt to use PostgreSQL instead of SQLite
- [x] Use WSGI for webserver
- [ ] Consider Heroku

Spot instances of size `t2.medium` has hourly rate of $0.0139 (~$10 per month) so I am going to use that.

**Comment by xuganyu96** [comment]
The data model seems to be running into issues with PostgreSQL:

```
Traceback (most recent call last):
  File "/Users/ganyuxu/.conda/envs/drop-in/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ganyuxu/Documents/projects/untitled-badminton-app/untitled/db.py", line 36, in init_db
    Base.metadata.create_all(engine) 
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4780, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 3107, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2110, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 850, in visit_metadata
    _is_metadata_operation=True,
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1286, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1384, in _execute_ddl
    compiled,
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2024, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
    cursor, statement, parameters, context
  File "/Users/ganyuxu/.conda/envs/drop-in/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "courts"

[SQL: 
CREATE TABLE tickets (
        is_valid BOOLEAN NOT NULL, 
        created_ts TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
        expired_ts TIMESTAMP WITHOUT TIME ZONE, 
        last_modified_ts TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
        _id SERIAL NOT NULL, 
        gym_id VARCHAR(128) NOT NULL, 
        court_id INTEGER, 
        owner_id INTEGER NOT NULL, 
        root_id INTEGER NOT NULL, 
        status VARCHAR(16) NOT NULL, 
        canceled_ts TIMESTAMP WITHOUT TIME ZONE, 
        activated_ts TIMESTAMP WITHOUT TIME ZONE, 
        PRIMARY KEY (_id), 
        FOREIGN KEY(gym_id) REFERENCES gyms (_id), 
        FOREIGN KEY(court_id) REFERENCES courts (_id), 
        FOREIGN KEY(owner_id) REFERENCES users (_id), 
        FOREIGN KEY(root_id) REFERENCES users (_id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
```
